### ISSUE TITLE
Using external sound card and usb to serial adapters

### ISSUE THREAD

**Issue by kb2sdr** [e3ndr/SurfaceRT-Images#2]
Is there a way to get an external USB sound card and USB to serial devices working? When I run dmesg the system appears to see the devices but doesn't seem to go any further than that. I can not select the devices in any software.

**Comment by e3ndr** [comment]
this would be a raspbian issue. check that you have the correct alsa/pulse packages installed. for reference, the surface is pretty similar to the pi 1 or 0, so use that when googling :^)
