### ISSUE TITLE
Cannot modify startup.nsh 

### ISSUE THREAD

**Issue by JoshJSL** [e3ndr/SurfaceRT-Images#3]
Hello, 
When trying to follow step 4 on [How to move installation to internal storage](https://github.com/e3ndr/SurfaceRT-Images/blob/main/Raspbian.md#how-to-move-the-installation-to-your-internal-storage), I change the startup.nsh file but it returns to the original content.
I don't know much Linux, I'd appreciate your help c:

**Comment by e3ndr** [comment]
Hey! Can you verify that you:
 - Used the `dd` command to copy the drive to the internal storage (eMMC)
 - Mounted the eMMC
 - Used `cd` to navigate to the eMMC.
